/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package code.View.ChildForms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.ButtonGroup;
import javax.swing.JList;
import javax.swing.ToolTipManager;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author hunter
 */
public class OptionIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form OptionIF
     * @param size
     */
    public OptionIF(Dimension size) {
        initComponents();
        initInternalPanel();
        this.setSize(size);
        initToolTipState();
    }

    private void initToolTipState(){
        UIManager.put("ToolTip.font", new Font("Monospaced", Font.BOLD, 14));
        ToolTipManager.sharedInstance().setInitialDelay(0);
    }
    
    private void initInternalPanel(){
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        process_type = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OptionList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bruteforce = new javax.swing.JRadioButton();
        encryption = new javax.swing.JRadioButton();
        decryption = new javax.swing.JRadioButton();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OptionList.setBackground(new java.awt.Color(0, 0, 0));
        OptionList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        OptionList.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        OptionList.setForeground(new java.awt.Color(255, 255, 255));
        OptionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Shift Cipher (Ascii Based)", "Shift Cipher", "Vigenere Cipher (Ascii Based)", "Vigenere Cipher", "Vernam Cipher (Ascii Based)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        OptionList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        OptionList.setSelectionBackground(new java.awt.Color(0, 0, 0));
        OptionList.setSelectionForeground(new java.awt.Color(0, 255, 102));
        OptionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OptionListMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(OptionList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 350, 150));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> <body> Use the mouse or arrow keys for navigation </body> </html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 390, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>\n<body>\n<font size=\"6\" color=red>|--------------------------------------|</font>\n</body>\n</html>");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 390, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>\n<body>\n<font size=\"6\" color=red>|--------------------------------------|</font>\n</body>\n</html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 390, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 238, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELECT YOU DESIRED CIPHER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 390, 40));

        process_type.add(bruteforce);
        bruteforce.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bruteforce.setForeground(new java.awt.Color(255, 255, 255));
        bruteforce.setText("Bruteforce");
        bruteforce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bruteforceMouseEntered(evt);
            }
        });
        jPanel1.add(bruteforce, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        process_type.add(encryption);
        encryption.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        encryption.setForeground(new java.awt.Color(255, 255, 255));
        encryption.setText("Encryption");
        encryption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encryptionMouseEntered(evt);
            }
        });
        jPanel1.add(encryption, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        process_type.add(decryption);
        decryption.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        decryption.setForeground(new java.awt.Color(255, 255, 255));
        decryption.setText("Decryption");
        decryption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                decryptionMouseEntered(evt);
            }
        });
        jPanel1.add(decryption, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OptionListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionListMouseEntered
        OptionList.setToolTipText("Listed are CipherTypes");
    }//GEN-LAST:event_OptionListMouseEntered

    private void encryptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encryptionMouseEntered
        encryption.setToolTipText("Process Type");
    }//GEN-LAST:event_encryptionMouseEntered

    private void bruteforceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bruteforceMouseEntered
        bruteforce.setToolTipText("Process Type");
    }//GEN-LAST:event_bruteforceMouseEntered

    private void decryptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decryptionMouseEntered
        decryption.setToolTipText("Process Type");
    }//GEN-LAST:event_decryptionMouseEntered

    public JList getOptionList(){
        return this.OptionList;
    }
    
    public String getType(){
        return encryption.isSelected() ? encryption.getText() : 
               decryption.isSelected() ? decryption.getText() : 
               bruteforce.isSelected() ? bruteforce.getText() : null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> OptionList;
    private javax.swing.JRadioButton bruteforce;
    private javax.swing.JRadioButton decryption;
    private javax.swing.JRadioButton encryption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup process_type;
    // End of variables declaration//GEN-END:variables
}
