/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code.View;

import code.View.ChildForms.IntroIF;
import code.View.ChildForms.OptionIF;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author hunter
 */
public class ParentForm extends javax.swing.JFrame {
    private OptionIF options;
    /**
     * Creates new form ParentForm
     */
    public ParentForm() {
        initComponents();
        initHeaderIconImage();
        DefTxtFieldState();
        initComponentsStyle();
    }
    
    private void DefTxtFieldState(){
        keyField.setEditable(false);
        textField.setEditable(false);
        textField.setEnabled(false);
        keyField.setEnabled(false);
    }
    
    private void initHeaderIconImage(){
        setFont(new Font("Agency FB", 1, 30));
        setTitle("SHADOWCRYPT");
        setIconImage(new ImageIcon(".//icon//logo.jpg").getImage());
    }
    
    private void initComponentsStyle(){
        this.keyField.putClientProperty("JComponent.roundRect", true);
        this.keyField.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON,true);
        this.textField.putClientProperty("JComponent.roundRect", true);
        this.textField.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON,true);
    }
    
    public void setInputFieldPlaceHolder(String msg){
        textField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, msg);
    }
    
    public void setKeyFieldPlaceHolder(String msg){
        keyField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, msg);
    }
    
    public void setUpIntro(){
        IntroIF intro = new IntroIF(this.getSize());
        DeskPanel.removeAll();
        DeskPanel.add(intro).setVisible(true);
    }
    
    public void setUpOptionPage(){
        options = new OptionIF(this.getSize());
        DeskPanel.removeAll();
        DeskPanel.add(options).setVisible(true);
    }
    
    public void appendLogInfo(String info){
        sysLogs.append(info);
    }
    
    public void setLogInfo(String info){
        sysLogs.setText(info);
    }
    
    public void clrLogInfo(){
        sysLogs.setText("");
    }
    
    public void setSysLogsColor(Color color){
        sysLogs.setForeground(color);
    }
    
    public void appendProcessInfo(String info){
        processLogs.append(info);
    }
    
    public void setProcessInfo(String info){
        processLogs.setText(info);
    }
    
    public void clrProcessInfo(){
        processLogs.setText("");
    }
    
    public void setProcessLogsColor(Color color){
        processLogs.setForeground(color);
    }
    
    public void setResult(String rs){
        resultField.setText(rs);
    }
    
    public void appendResult(String rs){
        resultField.append(rs);
    }
    
    public void clrResult(){
        resultField.setText("");
    }
    
    public OptionIF getOptionIF(){
        return this.options;
    }
    
    public JButton getBtn(){
        return this.enterBtn;
    }
    
    public JTextField getInputField(){
        return this.textField;
    }
    
    public JTextField getKeyField(){
        return this.keyField;
    }
    
    public void enableInputFields(){
        textField.setEnabled(true);
        keyField.setEnabled(true);
        textField.setEditable(true);
        keyField.setEditable(true);
    }
    
    public void disableInputFields(){
        textField.setEditable(false);
        keyField.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DeskPanel = new javax.swing.JDesktopPane();
        keyField = new javax.swing.JTextField();
        enterBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sysLogs = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        processLogs = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultField = new javax.swing.JTextArea();
        textField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DeskPanel.setBackground(new java.awt.Color(153, 153, 153));
        DeskPanel.setForeground(new java.awt.Color(153, 153, 153));
        DeskPanel.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        javax.swing.GroupLayout DeskPanelLayout = new javax.swing.GroupLayout(DeskPanel);
        DeskPanel.setLayout(DeskPanelLayout);
        DeskPanelLayout.setHorizontalGroup(
            DeskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DeskPanelLayout.setVerticalGroup(
            DeskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jPanel1.add(DeskPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 6, 781, -1));

        keyField.setBackground(new java.awt.Color(0, 0, 0));
        keyField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        keyField.setForeground(new java.awt.Color(255, 255, 255));
        keyField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keyFieldMouseEntered(evt);
            }
        });
        jPanel1.add(keyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 445, 242, 48));

        enterBtn.setBackground(new java.awt.Color(0, 153, 255));
        enterBtn.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        enterBtn.setForeground(new java.awt.Color(255, 255, 255));
        enterBtn.setText("ENTER");
        enterBtn.setEnabled(false);
        jPanel1.add(enterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 450, 85, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SYSTEM LOGS");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        sysLogs.setEditable(false);
        sysLogs.setBackground(new java.awt.Color(0, 0, 0));
        sysLogs.setColumns(20);
        sysLogs.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        sysLogs.setForeground(new java.awt.Color(255, 255, 255));
        sysLogs.setLineWrap(true);
        sysLogs.setRows(5);
        sysLogs.setWrapStyleWord(true);
        sysLogs.setFocusable(false);
        sysLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sysLogsMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(sysLogs);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 698));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel3.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROCESS LOGS");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        processLogs.setEditable(false);
        processLogs.setBackground(new java.awt.Color(0, 0, 0));
        processLogs.setColumns(20);
        processLogs.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        processLogs.setForeground(new java.awt.Color(255, 255, 255));
        processLogs.setLineWrap(true);
        processLogs.setRows(5);
        processLogs.setWrapStyleWord(true);
        processLogs.setFocusable(false);
        processLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                processLogsMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(processLogs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 6, -1, 698));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        resultField.setEditable(false);
        resultField.setBackground(new java.awt.Color(0, 0, 0));
        resultField.setColumns(20);
        resultField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        resultField.setForeground(new java.awt.Color(255, 255, 255));
        resultField.setLineWrap(true);
        resultField.setRows(5);
        resultField.setText("Results are here...");
        resultField.setWrapStyleWord(true);
        jScrollPane3.setViewportView(resultField);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 499, 781, -1));

        textField.setBackground(new java.awt.Color(0, 0, 0));
        textField.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        textField.setForeground(new java.awt.Color(255, 255, 255));
        textField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textFieldMouseEntered(evt);
            }
        });
        jPanel1.add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 445, 442, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1222, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keyFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyFieldMouseEntered
        keyField.setToolTipText("Input Field for your key");
    }//GEN-LAST:event_keyFieldMouseEntered

    private void textFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMouseEntered
        textField.setToolTipText("Input Field for your text");
    }//GEN-LAST:event_textFieldMouseEntered

    private void processLogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processLogsMouseEntered
       processLogs.setToolTipText("Ouput Field for your process status");
    }//GEN-LAST:event_processLogsMouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setToolTipText("Ouput Field for any errors occured during runtime");
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       jLabel2.setToolTipText("Ouput Field for your process status");
    }//GEN-LAST:event_jLabel2MouseEntered

    private void sysLogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sysLogsMouseEntered
        sysLogs.setToolTipText("Ouput Field for any errors occured during runtime");
    }//GEN-LAST:event_sysLogsMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskPanel;
    private javax.swing.JButton enterBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField keyField;
    private javax.swing.JTextArea processLogs;
    private javax.swing.JTextArea resultField;
    private javax.swing.JTextArea sysLogs;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
